language: python

python:
  - "2.7"

install:
  - pip install ansible

script:
  - ansible-playbook --syntax-check --list-tasks -i tests/ansible.inventory setup.yml

notifications:
  email:
    - tomaz+travisci@tomaz.me
